name: scan_pdf
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  easy_localization: ^3.0.7
  open_filex: ^4.5.0
  pdf: ^3.11.1
  camera: ^0.11.0+2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  http_parser: ^4.1.0
  material_color_utilities: ^0.12.0
  string_scanner: ^1.3.0
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  test_api: ^0.7.3    

flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/translations/
  - assets/imgs/